trigger: none

stages:
- stage: Terraform
  displayName: "Terraform Lifecycle"
  jobs:
  - job: TerraformJob
    displayName: "Deploy Azure Resources"
    pool:
      name: 'adarsh'  # self-hosted agent

    steps:
    # Checkout the repository
    - checkout: self
      clean: true
      fetchTags: false

    # Terraform Init
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        backendServiceArm: 'AzureARM'
        backendAzureRmResourceGroupName: 'OCEAN'
        backendAzureRmStorageAccountName: 'adarshmoger'
        backendAzureRmContainerName: 'maxi'
        backendAzureRmKey: 'k8sinfra.tfstate'
        command: 'init'

    # Terraform Validate
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'

    # Terraform Plan
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'AzureARM'
        vars: |
          public_key_path=/home/adarshmoger/.ssh/id_rsa.pub
          private_key_path=/home/adarshmoger/.ssh/id_rsa
        varFiles: 'terraform.tfvars'

    # Terraform Apply
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'AzureARM'
        commandOptions: '-auto-approve'
        vars: |
          public_key_path=/home/adarshmoger/.ssh/id_rsa.pub
          private_key_path=/home/adarshmoger/.ssh/id_rsa
        varFiles: 'terraform.tfvars'

