trigger: none

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    pool:
      name: 'adarsh'  # self-hosted agent

    steps:
    - task: Checkout@1

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureARM'  # your service connection
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logged into Azure"

    - script: |
        terraform init -backend-config="resource_group_name=OCEAN" \
                       -backend-config="storage_account_name=adarshmoger" \
                       -backend-config="container_name=maxi" \
                       -backend-config="key=k8sinfra.tfstate"
      displayName: "Terraform Init"

    - script: terraform validate
      displayName: "Terraform Validate"

    - script: |
        terraform plan -var "public_key_path=/home/adarshmoger/.ssh/id_rsa.pub" \
                       -var "private_key_path=/home/adarshmoger/.ssh/id_rsa" \
                       -var-file="terraform.tfvars"
      displayName: "Terraform Plan"

    - script: |
        terraform apply -auto-approve -var "public_key_path=/home/adarshmoger/.ssh/id_rsa.pub" \
                                      -var "private_key_path=/home/adarshmoger/.ssh/id_rsa" \
                                      -var-file="terraform.tfvars"
      displayName: "Terraform Apply"

