trigger: none  # Run manually for cleanup

stages:
- stage: TerraformDestroy
  displayName: "Terraform Destroy Stage"
  jobs:
  - job: TerraformDestroyJob
    displayName: "Destroy Existing Azure Infrastructure"
    pool:
      name: 'adarsh'  # your self-hosted agent

    steps:
    # -------------------------
    # 1️⃣ Checkout Repository
    # -------------------------
    - checkout: self
      clean: true
      displayName: "Checkout Terraform Repository"

    # -------------------------
    # 2️⃣ Terraform Init (Reconfigure)
    # -------------------------
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Init (Reconfigure)"
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-reconfigure -upgrade'
        backendServiceArm: 'AzureARM'  # your service connection name
        backendAzureRmResourceGroupName: 'OCEAN'
        backendAzureRmStorageAccountName: 'adarshmoger'
        backendAzureRmContainerName: 'maxi'
        backendAzureRmKey: 'k8sinfra.tfstate'

    # -------------------------
    # 3️⃣ Terraform Destroy
    # -------------------------
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Destroy (Auto Approve)"
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        environmentServiceNameAzureRM: 'AzureARM'
        commandOptions: '-auto-approve'
        vars: |
          public_key_path=/home/adarshmoger/.ssh/id_rsa.pub
          private_key_path=/home/adarshmoger/.ssh/id_rsa
        varFiles: |
          terraform.tfvars
        workingDirectory: '$(System.DefaultWorkingDirectory)'

