trigger: none  # Run manually for now; you can enable CI/CD triggers later

stages:
- stage: Terraform
  displayName: "Terraform Lifecycle"
  jobs:
  - job: TerraformJob
    displayName: "Deploy Azure Infrastructure"
    pool:
      name: 'adarsh'  # self-hosted agent name

    steps:
    # -------------------------
    # 1️⃣ Checkout Repository
    # -------------------------
    - checkout: self
      clean: true
      fetchTags: false
      displayName: "Checkout Terraform Repository"

    # -------------------------
    # 2️⃣ Terraform Init (with -reconfigure)
    # -------------------------
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Init (Reconfigure)"
      inputs:
        provider: 'azurerm'
        command: 'init'
        commandOptions: '-upgrade'
        backendServiceArm: 'AzureARM'  # your service connection name
        backendAzureRmResourceGroupName: 'OCEAN'
        backendAzureRmStorageAccountName: 'adarshmoger'
        backendAzureRmContainerName: 'maxi'
        backendAzureRmKey: 'k8sinfra.tfstate'

    # -------------------------
    # 3️⃣ Terraform Validate
    # -------------------------
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'

    # -------------------------
    # 4️⃣ Terraform Plan
    # -------------------------
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'AzureARM'
        vars: |
          public_key_path=/home/adarshmoger/.ssh/id_rsa.pub
          private_key_path=/home/adarshmoger/.ssh/id_rsa
        varFiles: |
          terraform.tfvars
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    # -------------------------
    # 5️⃣ Terraform Apply
    # -------------------------
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTask@5
      displayName: "Terraform Apply"
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'AzureARM'
        commandOptions: '-auto-approve'
        vars: |
          public_key_path=/home/adarshmoger/.ssh/id_rsa.pub
          private_key_path=/home/adarshmoger/.ssh/id_rsa
        varFiles: |
          terraform.tfvars
        workingDirectory: '$(System.DefaultWorkingDirectory)'

